# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class tela_login(object):
    def setupUi(self, tela_login):
        tela_login.setObjectName("tela_login")
        tela_login.resize(900, 768)
        tela_login.setMaximumSize(QtCore.QSize(1024, 768))
        self.centralwidget = QtWidgets.QWidget(tela_login)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(540, 650))
        self.frame.setMaximumSize(QtCore.QSize(1024, 748))
        self.frame.setStyleSheet("background-color: rgb(4, 14, 66);\n"
"color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(270, 190, 371, 421))
        self.frame_2.setStyleSheet("background-color: rgba(1, 0, 0, 99);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(110, 250, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(0, 0, 0);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid rgb(32, 74, 135);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(60, 100, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 170, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 40, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgba(1, 0, 0, 99);\n"
"padding: 5px;")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 320, 141, 41))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(52, 101, 164);    \n"
"border-radius: 10px;\n"
"border: 2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid rgb(32, 74, 135);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(370, 80, 151, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../imagens/icon_title.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.frame_2.raise_()
        self.verticalLayout.addWidget(self.frame)
        tela_login.setCentralWidget(self.centralwidget)

        self.retranslateUi(tela_login)
        QtCore.QMetaObject.connectSlotsByName(tela_login)

    def retranslateUi(self, tela_login):
        _translate = QtCore.QCoreApplication.translate
        tela_login.setWindowTitle(_translate("tela_login", "MainWindow"))
        self.pushButton.setText(_translate("tela_login", "Entrar"))
        self.lineEdit.setPlaceholderText(_translate("tela_login", "User"))
        self.lineEdit_2.setPlaceholderText(_translate("tela_login", "password"))
        self.lineEdit_3.setText(_translate("tela_login", "Login"))
        self.pushButton_2.setText(_translate("tela_login", "Cadastrar-se"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tela_login = QtWidgets.QMainWindow()
    ui = Ui_tela_login()
    ui.setupUi(tela_login)
    tela_login.show()
    sys.exit(app.exec_())
