# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_extrato.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class tela_extrato(object):
    def setupUi(self, Tela_extrato):
        Tela_extrato.setObjectName("Tela_extrato")
        Tela_extrato.resize(900, 748)
        Tela_extrato.setMinimumSize(QtCore.QSize(540, 650))
        Tela_extrato.setMaximumSize(QtCore.QSize(1024, 748))
        self.centralwidget = QtWidgets.QWidget(Tela_extrato)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(4, 14, 66);\n"
"color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(350, 20, 201, 131))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../imagens/icon_extrato2.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(210, 150, 481, 301))
        self.frame_2.setStyleSheet("background-color: rgba(1, 0, 0, 99);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(130, 110, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-radius: 5px;\n"
"background-color: rgba(255, 255, 255, 198);\n"
"border: 1px solid rgba(3, 20, 52, 150);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(16, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgba(1, 0, 0, 99);\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(0, 20, 481, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 510, 141, 41))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(52, 101, 164);    \n"
"border-radius: 10px;\n"
"border: 2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(52, 101, 164);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid rgb(32, 74, 135);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.frame)
        Tela_extrato.setCentralWidget(self.centralwidget)

        self.retranslateUi(Tela_extrato)
        QtCore.QMetaObject.connectSlotsByName(Tela_extrato)

    def retranslateUi(self, Tela_extrato):
        _translate = QtCore.QCoreApplication.translate
        Tela_extrato.setWindowTitle(_translate("Tela_extrato", "MainWindow"))
        self.label_3.setText(_translate("Tela_extrato", "Saldo"))
        self.label.setText(_translate("Tela_extrato", "Extrato"))
        self.pushButton_2.setText(_translate("Tela_extrato", "Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tela_extrato = QtWidgets.QMainWindow()
    ui = Ui_Tela_extrato()
    ui.setupUi(Tela_extrato)
    Tela_extrato.show()
    sys.exit(app.exec_())
