-- MySQL Script generated by MySQL Workbench
-- seg 25 abr 2022 15:12:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Banco` DEFAULT CHARACTER SET utf8 ;
USE `Banco` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cliente` (
  `Id_cliente` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `sobrenome` VARCHAR(30) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cpf` varchar(14) UNIQUE NOT NULL,
  PRIMARY KEY (`Id_cliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`Conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conta` (
  `Id_conta` INT NOT NULL AUTO_INCREMENT,
  `saldo` FLOAT(20,2) NOT NULL,
  `limite` FLOAT(20,2) NOT NULL,
  `Cliente_Id_cliente` INT UNIQUE NOT NULL,
  `senha` VARCHAR(3000) NOT NULL,
  `user_login` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id_conta`, `user_login`),
  INDEX `fk_Conta_Cliente1_idx` (`Cliente_Id_cliente` ASC) VISIBLE,
  UNIQUE INDEX `Id_conta_UNIQUE` (`Id_conta` ASC) VISIBLE,
  UNIQUE INDEX `user_login_UNIQUE` (`user_login` ASC) VISIBLE,
  CONSTRAINT `fk_Conta_Cliente1`
    FOREIGN KEY (`Cliente_Id_cliente`)
    REFERENCES `Cliente` (`Id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historico` (
  `id_historico` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `transacao` VARCHAR(500) NOT NULL,
  `data_transacao` DATE NOT NULL,
  `Conta_Id_conta` INT NOT NULL,
  PRIMARY KEY (`id_historico`, `Conta_Id_conta`),
  UNIQUE INDEX `id_historico_UNIQUE` (`id_historico` ASC) VISIBLE,
  INDEX `fk_historico_Conta1_idx` (`Conta_Id_conta` ASC) VISIBLE,
  CONSTRAINT `fk_historico_Conta1`
    FOREIGN KEY (`Conta_Id_conta`)
    REFERENCES `Conta` (`Id_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
